### ISSUE TITLE
运行打开报错，500

### ISSUE THREAD

**Issue by Loni0527** [iawia002/Diana#28]
非常喜欢您的这个模板，但当我下载后想运行却出现500。
由于对Python不太懂，所以我无法来修改这个错误。
请大神指教
![_20180724161533](https://user-images.githubusercontent.com/29487688/43125650-3d112d80-8f5d-11e8-861a-6f4e1c068557.png)

**Comment by iawia002** [comment]
建立、迁移数据库，初始化用户那些做了吗

**Comment by Loni0527** [comment]
我今天把数据库换成了mysql，数据是能读取出来，但前台页面又没了T-T
![tim 20180725093442](https://user-images.githubusercontent.com/29487688/43174933-33495646-8fef-11e8-94f7-502bac134516.png)
```
{
  "articles": [
    {
      "article_id": 1,
      "compiled_content": "'''\n<h1 id=\"hello\">hello</h1>\n<blockquote>\n<p>hello</p>\n</blockquote>\n<p>hello</p>\n        '''",
      "create_time": "2018-07-25 09:30:21",
      "introduction": "<p>hello</p>",
      "markdown_content": "'''\n# hello\n> hello\n\nhello\n        '''",
      "tags": [],
      "title": "hello",
      "update_time": "2018-07-25 09:30:21",
      "user_id": "1",
      "views": 0
    }
  ],
  "bg": {
    "name": "电玩系列",
    "url": "http://img.l.jifangcheng.com/o_1a7rcga441ldd7fb1fb8mb4q2a.jpg"
  },
  "login": false,
  "next_page": 2,
  "user": {
    "avatar": "http://img.l.jifangcheng.com/Katarina.png",
    "introduction": "hello",
    "join_time": null,
    "last_login": null,
    "user_id": 1,
    "username": "admin"
  }
}
```
我只修改了下面两个地方
![tim 20180725094144](https://user-images.githubusercontent.com/29487688/43174934-33b2b172-8fef-11e8-968a-17f2823eee0c.png)
![tim 20180725094219](https://user-images.githubusercontent.com/29487688/43174935-341049fe-8fef-11e8-8f67-0982e8086aa9.png)

前面项目所有的文件
![tim 20180725094520](https://user-images.githubusercontent.com/29487688/43174989-8171b28c-8fef-11e8-8c33-dc1a058cec73.png)
![tim 20180725094528](https://user-images.githubusercontent.com/29487688/43174990-81d8e218-8fef-11e8-982a-abc54f3fbf94.png)

**Comment by Loni0527** [comment]
`npm install`
`npm run dev --Diana:app=blog`
`npm run build --Diana:app=blog`
以上三个命令都是成功执行的。
请帮忙看看是哪里出了问题。谢谢!

**Comment by Loni0527** [comment]
拿之前下载过的项目改了下就好了，不知道是什么情况。
但是怎么也打不开后台的登录页面是怎么回事呢

**Comment by iawia002** [comment]
现在最新的版本是前后端分离的（#23 之后），还需要启动前端，README 是以前的版本的，还没更新

**Comment by Loni0527** [comment]
谢谢，已经可以运行，正在想着加一个后台管理。
